# Generated by Django 4.2 on 2023-05-31 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genbills', '0002_carmovements'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
