# Generated by Django 4.1.7 on 2023-06-21 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RailVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_mark', models.CharField(max_length=4)),
                ('id_number', models.PositiveIntegerField()),
                ('aar_type', models.CharField(max_length=2)),
                ('cargo', models.CharField(max_length=12)),
                ('loaded', models.BooleanField()),
                ('location', models.PositiveIntegerField()),
                ('location_str', models.CharField(max_length=36)),
                ('last_loaded_unloaded', models.PositiveIntegerField()),
                ('ready_for_pickup', models.BooleanField()),
                ('img_url', models.URLField()),
            ],
        ),
    ]
