# Generated by Django 4.1.7 on 2023-06-25 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rollingstock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='railvehicle',
            name='location',
            field=models.PositiveIntegerField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layout.location')),
        ),
    ]
