# Generated by Django 4.1.7 on 2023-06-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rollingstock', '0002_alter_railvehicle_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='railvehicle',
            name='location',
            field=models.PositiveIntegerField(),
        ),
    ]
