# Generated by Django 4.1.7 on 2023-06-21 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('macro_location', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('locations', models.ManyToManyField(to='layout.location')),
            ],
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=32)),
                ('loaded', models.BooleanField()),
                ('min_cars', models.PositiveIntegerField()),
                ('max_cars', models.PositiveIntegerField()),
                ('frequency', models.FloatField()),
                ('name', models.CharField(max_length=32)),
                ('days', models.CharField(max_length=7)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layout.layout')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layout.location')),
            ],
        ),
    ]
