# Generated by Django 4.2 on 2023-05-31 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0002_location_layout_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=32)),
                ('loaded', models.BooleanField()),
                ('min_cars', models.PositiveIntegerField()),
                ('max_cars', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=32)),
                ('days', models.CharField(max_length=7)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layout.layout')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layout.location')),
            ],
        ),
    ]
