# Generated by Django 4.1.7 on 2023-06-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0003_demand'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='frequency',
            field=models.FloatField(default=0.5),
            preserve_default=False,
        ),
    ]
